from odoo import api, fields, models, _
from odoo.exceptions import UserError


class Booking(models.Model):
    _name = 'freight.booking'
    _description = 'Booking'
    _inherit = ['mail.thread', 'mail.activity.mixin', 'freight.transport.mixin']
    _order = 'booking_date desc'

    # General info
    name = fields.Char(
        string='Booking No', required=True, copy=False, default=lambda self: _('New'),
        help="Internal booking number generated by the system.")
    booking_date = fields.Date(
        string='Booking Date',
        required=True,
        default=fields.Date.context_today,
        tracking=True
    )
    booking_ref = fields.Char(
        string='Booking Reference',
        copy=False, tracking=True,
        help="External booking reference number provided by the carrier."
    )
    responsible_id = fields.Many2one(
        'res.users', string='Responsible', tracking=True, default=lambda self: self.env.user)
    carrier_resolution_required = fields.Selection([
        ('none', 'No Action Required'),
        ('notify_only', 'Notify Stakeholders Only'),
    ], string='Carrier Resolution', compute='_compute_carrier_resolution_required', compute_sudo=True,
        help="Indicates what action is needed to resolve carrier configuration.")

    stakeholder_user_ids = fields.Many2many(
        'res.users', string='Stakeholders', domain=[('share', '=', False)],
        compute='_compute_stakeholder_user_ids', compute_sudo=True,
        help="Users who should be notified about booking issues. Auto-populated but can be customized.")

    state = fields.Selection([
        ('draft', 'Draft'),
        ('confirmed', 'Confirmed'),
        ('done', 'Done'),
        ('cancelled', 'Cancelled')
    ], string='Status', required=True, default='draft', tracking=True,
        help="Indicates the current processing state of the booking:\n"
        "- Draft: Booking is being prepared and editable.\n"
        "- Confirmed: Booking has been confirmed and sent to the carrier.\n"
        "- Done: Transport has been completed.\n"
        "- Cancelled: Booking has been cancelled. Typically used when the shipment is no longer needed or details were incorrect.")
    multiple_leg_route = fields.Boolean(
        string='Multiple Leg Route',
        help="Select if this booking covers multiple transport legs (e.g., pickup, main leg, delivery). "
        "Allows defining separate schedules for each leg route.")

    # Bill Of Lading
    master_bill_number = fields.Char(
        string='Master Bill of Lading', tracking=True,
        help="Bill of Lading provided by the carrier for this booking")

    # Reference info
    shipment_id = fields.Many2one(
        'freight.shipment', string='Shipment', tracking=True,
        help="Reference to the shipment associated with this booking."
    )
    cargo_mode = fields.Selection(related='shipment_id.cargo_mode')
    cargo_note_details = fields.Text(string='Cargo Note Details', help="Free-form text to summarize cargo details.")
    package_ids = fields.Many2many(
        'freight.package', 'freight_booking_package_rel', 'booking_id', 'package_id',
        string='Packages'
    )
    cargo_commodity_ids = fields.Many2many(
        'cargo.commodity', 'freight_booking_cargo_commodity_rel', 'booking_id', 'cargo_commodity_id',
        string='Cargo Details', domain="[('shipment_id', '=', shipment_id)]"
    )
    freight_route_ids = fields.Many2many(
        'freight.route', 'freight_route_booking_rel', 'booking_id', 'route_id', string='Routes',
        help="Routes assigned to this booking, especially for multi-leg transportation.")

    consignee_id = fields.Many2one(related='shipment_id.consignee_id')
    shipper_id = fields.Many2one(related='shipment_id.shipper_id')

    # Schedule
    etd = fields.Datetime(
        compute='_compute_schedule',
        store=True,
        readonly=False,
        help="Estimated Time of Departure. The planned date and time when the shipment or transport is expected to leave."
    )

    eta = fields.Datetime(
        compute='_compute_schedule',
        store=True,
        readonly=False,
        help="Estimated Time of Arrival. The planned date and time when the shipment or transport is expected to arrive at the destination."
    )

    cutoff = fields.Datetime(
        compute='_compute_schedule',
        store=True,
        readonly=False,
        help="Cut-off Time. The deadline by which cargo, documents, or actions must be completed to ensure the shipment can be processed or depart as scheduled."
    )

    # ===============================================
    # ============ Compute Methods ==================
    # ===============================================

    @api.depends('cargo_commodity_ids.weight', 'cargo_commodity_ids.volume', 'package_ids.volume', 'package_ids.weight')
    def _compute_cargo_totals(self):
        super()._compute_cargo_totals()
        for record in self:
            if record.package_ids:
                record.total_weight = sum(record.package_ids.mapped('weight'))
                record.total_volume = sum(record.package_ids.mapped('volume'))
            elif record.cargo_commodity_ids:
                record.total_weight = sum(record.cargo_commodity_ids.mapped('weight'))
                record.total_volume = sum(record.cargo_commodity_ids.mapped('volume'))

    @api.depends('cargo_commodity_ids.quantity', 'package_ids')
    def _compute_counts(self):
        for r in self:
            r.total_packages = len(r.package_ids)
            if r.cargo_mode == 'structured_entry':
                r.total_cargo_commodities = sum(r.cargo_commodity_ids.mapped('quantity'))

    @api.depends(
        'freight_route_ids.eta', 'freight_route_ids.etd', 'freight_route_ids.cutoff',
        'state', 'multiple_leg_route',
    )
    def _compute_schedule(self):
        for record in self:
            if record.multiple_leg_route and record.state == 'draft':
                if record.freight_route_ids:
                    route_etds = [route.etd for route in record.freight_route_ids if route.etd]
                    route_etas = [route.eta for route in record.freight_route_ids if route.eta]
                    route_cutoffs = [route.cutoff for route in record.freight_route_ids if route.cutoff]

                    record.etd = min(route_etds) if route_etds else False
                    record.eta = max(route_etas) if route_etas else False
                    record.cutoff = min(route_cutoffs) if route_cutoffs else False
                else:
                    record.etd = False
                    record.eta = False
                    record.cutoff = False

    def _compute_carrier_resolution_required(self):
        """Base implementation - no resolution needed for basic freight operations"""
        for r in self:
            r.carrier_resolution_required = 'none'

    @api.depends('responsible_id', 'shipment_id.responsible_id',
        'sale_order_line_id.order_id.user_id')
    def _compute_stakeholder_user_ids(self):
        for r in self:
            r.stakeholder_user_ids = (r.responsible_id
                | r.shipment_id.responsible_id
                | r.sale_order_line_id.order_id.user_id)

    # ===============================================
    # ============ CRUD Methods =====================
    # ===============================================

    @api.model_create_multi
    def create(self, vals_list):
        """Create new booking records.
        Automatically generate booking numbers if not provided.
        """
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New'):
                vals['name'] = self.env['ir.sequence'].next_by_code('freight.booking') or _('New')
        return super().create(vals_list)

    def write(self, vals):
        """Override write method to sync info after updating booking"""
        result = super().write(vals)
        sync_fields = self._get_sync_fields()
        if any(field in vals for field in sync_fields):
            self._sync_info()
        return result

    def _get_sync_fields(self):
        """Return list of fields that need synchronization when changed"""
        return [
            'transport_mode', 'service_type', 'route_id', 'origin_id', 'destination_id',
            'etd', 'eta', 'cutoff', 'vessel_name', 'vessel_voyage_number',
            'air_name', 'air_voyage_number', 'truck_name', 'driver_id', 'master_bill_number',
            'agent_id', 'carrier_id', 'port_of_loading_id', 'port_of_discharge_id'
        ]

    @api.ondelete(at_uninstall=False)
    def _unlink_check_state_booking(self):
        """Override unlink method to check if the booking is draft"""
        for record in self:
            if record.state != 'draft':
                raise UserError(_("You cannot delete booking %s that is not in draft state.") % record.name)

    # ===============================================
    # ============ Business Methods =================
    # ===============================================

    def _check_booking_validity(self):
        """Check if the booking is valid"""
        for r in self.filtered(lambda b: b.state == 'draft'):
            if r.multiple_leg_route and not r.freight_route_ids:
                raise UserError(_("Please set a Route for the Booking %s before sending it to the Carrier.") % r.name)
            if not r.carrier_id:
                raise UserError(_("Please set a Carrier for the Booking %s before sending it to the Carrier.") % r.name)

    def action_confirm(self):
        """Confirm booking"""
        self.ensure_one()
        self._check_booking_validity()

        if (not self.env.context.get('bypass_resolution_check')
                and self.carrier_resolution_required != 'none'):
            return self._open_confirm_resolve_wizard()

        self.state = 'confirmed'
        self._sync_info()

    def _open_confirm_resolve_wizard(self):
        return {
            'type': 'ir.actions.act_window',
            'name': _('Resolve Booking Confirmation'),
            'res_model': 'freight.booking.confirm.resolve.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_booking_id': self.id,
            }
        }

    def action_done(self):
        """Done booking"""
        self.state = 'done'

    def action_cancel(self):
        """Cancel booking"""
        self.state = 'cancelled'

    def action_draft(self):
        """Set booking to draft"""
        self.state = 'draft'

    def _sync_info(self):
        """
        Synchronize information from booking to shipment or route based on booking configuration.

        Scenarios:
        - Single-leg shipment: sync directly to the shipment.
        - Multi-leg shipment with one booking per leg: sync to the corresponding route.
        - Multi-leg shipment with multiple bookings: only sync carrier to routes.
        Other info set manually at route level.
        """
        confirmed_bookings = self.filtered(lambda b: b.state == 'confirmed')
        for booking in confirmed_bookings:
            sync_info_vals = {
                'transport_mode': booking.transport_mode,
                'service_type': booking.service_type,
                'route_id': booking.route_id.id,
                'origin_id': booking.origin_id.id,
                'destination_id': booking.destination_id.id,
                'etd': booking.etd,
                'eta': booking.eta,
                'cutoff': booking.cutoff,
                'vessel_name': booking.vessel_name,
                'vessel_voyage_number': booking.vessel_voyage_number,
                'air_name': booking.air_name,
                'air_voyage_number': booking.air_voyage_number,
                'truck_name': booking.truck_name,
                'driver_id': booking.driver_id.id,
                'agent_id': booking.agent_id.id,
                'carrier_id': booking.carrier_id.id
            }
            if not booking.shipment_id.multiple_leg_route:
                sync_info_vals.update({
                    'port_of_loading_id': booking.port_of_loading_id,
                    'port_of_discharge_id': booking.port_of_discharge_id,
                    'master_bill_number': booking.master_bill_number,
                })
                booking.shipment_id.write(sync_info_vals)
            elif booking.shipment_id.multiple_leg_route and not booking.multiple_leg_route:
                booking.freight_route_ids.write(sync_info_vals)
            elif booking.multiple_leg_route:
                booking.freight_route_ids.write({'carrier_id': booking.carrier_id.id})

    def _get_report_base_filename(self):
        """
        Get the base filename for the report when printing or downloading.
        """
        self.ensure_one()
        return f'Booking_Request_{self.name}'

    def _get_report_attachment_filename(self):
        """
        Get the attachment filename for caching the report.
        Return False to disable caching and always regenerate the report.
        """
        return False
