from . import stock_package_type
from . import product_template
from . import sale_order
from . import sale_order_line
from . import res_company
from . import res_config_settings
from . import account_analytic_account
from . import res_partner
from . import route_route
from . import freight_mixin
from . import hs_code
from . import cargo_type
from . import dg_class
from . import un_number
from . import freight_shipping_method
from . import freight_shipment_stage
from . import freight_shipment
from . import freight_booking
from . import cargo_template
from . import cargo_template_data
from . import cargo_template_data_line
from . import freight_package
from . import cargo_commodity
from . import freight_route
from . import freight_shipment_tracking
from . import freight_shipment_status_template
