from . import test_business_process
from . import test_access_rights
from . import test_features_on_shipment
from . import test_features_on_booking
from . import test_features_on_package_cargo
from . import test_features_on_freight_route
from . import test_freight_naming
from . import test_data_integrity
from . import test_unlink
